[features]
seeds = true
skip-lint = false

[programs.devnet]
pirate_faucet = "4qqkcdDu3porjEyRDpD7ScaDCU7jg8epBPF7HfCSLY7h"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/joesol/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/main.test.ts"